<!DOCTYPE html>
<html>
    <head>
        <title>Result</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <style>
               th {
                    background-color: #DCDCDC
                }
    </style>
    <body>
    <br><br>
    <input type="button" onclick="location.href='/'" value="Back to Main"/>
                <table border="5">
                    <th>Result</th>
                    <tr>${message}</tr>
                </table>
    </body>
</html>